# Generated by Django 4.2.20 on 2025-04-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keychains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acquired_in', models.CharField(max_length=100)),
                ('date_acquired', models.DateField()),
                ('material', models.CharField(choices=[('metal', 'Metal'), ('plastic', 'Plastic'), ('leather', 'Leather'), ('wood', 'Wood'), ('rubber', 'Rubber'), ('other', 'Other')], default='other', max_length=20)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('story', models.TextField(blank=True)),
                ('is_gift', models.BooleanField(default=False)),
            ],
        ),
    ]
