# Generated by Django 4.2.20 on 2025-04-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keychains',
            new_name='Keychain',
        ),
    ]
