# Generated by Django 4.2.20 on 2025-04-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_keychains_keychain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keychain',
            name='date_acquired',
        ),
        migrations.AddField(
            model_name='keychain',
            name='year_acquired',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
