# Generated by Django 4.2.20 on 2025-04-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_keychain_date_acquired_keychain_year_acquired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keychain',
            name='story',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='keychain',
            name='theme',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keychain',
            name='year_acquired',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
