# Generated by Django 4.2.20 on 2025-04-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_keychain_story_alter_keychain_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeychainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='keychain_images/')),
                ('caption', models.CharField(max_length=350)),
                ('keychain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.keychain')),
            ],
        ),
    ]
