# Generated by Django 4.2.20 on 2025-04-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_tag_keychain_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
    ]
